{"error":"list index out of range\nTraceback (most recent call last):\n  File \"/home/lighbgsz/max_app/business/views.py\", line 483, in send_rest_template\n    send_order_confirmation(media_path, data)\n  File \"/home/lighbgsz/max_app/business/functions.py\", line 860, in send_order_confirmation\n    \"text\": data.get(\"components\")[16]\n            ~~~~~~~~~~~~~~~~~~~~~~^^^^\nIndexError: list index out of range\n"}